<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R Para Ciencia de Datos - 20&nbsp; Iteración</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./22-model.html" rel="next">
<link href="./20-vectors.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17-program.html">Programar</a></li><li class="breadcrumb-item"><a href="./21-iteration.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Iteración</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R Para Ciencia de Datos</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bienvenida</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Explorar</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-visualize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Visualización de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-workflow-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Flujo de trabajo: conocimientos básicos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transformación de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-workflow-scripts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Flujo de trabajo: <em>Scripts</em></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Análisis exploratorio de datos (<em>EDA</em>)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-workflow-projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Flujo de trabajo: proyectos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Manejar o domar datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-wrangle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-tibble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Tibbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Importación de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Datos ordenados</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-relational-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Datos relacionales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Cadenas de caracteres</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Factores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-datetimes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Fechas y horas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Programar</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-program.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">(PART) Programar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-pipes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Pipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Funciones</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Vectores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-iteration.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Iteración</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Modelar</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-model-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Modelos: conceptos básicos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-model-building.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Construcción de modelos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-model-many.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Muchos modelos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Comunicar</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-communicate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-communicate-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Comunicar con gráficos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-rmarkdown-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Formatos de R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-rmarkdown-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Flujo de trabajo en R Markdown</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">20.1</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#prerrequisitos" id="toc-prerrequisitos" class="nav-link" data-scroll-target="#prerrequisitos"><span class="header-section-number">20.1.1</span> Prerrequisitos</a></li>
  </ul></li>
  <li><a href="#bucles-for" id="toc-bucles-for" class="nav-link" data-scroll-target="#bucles-for"><span class="header-section-number">20.2</span> Bucles <em>for</em></a>
  <ul class="collapse">
  <li><a href="#ejercicios" id="toc-ejercicios" class="nav-link" data-scroll-target="#ejercicios"><span class="header-section-number">20.2.1</span> Ejercicios</a></li>
  </ul></li>
  <li><a href="#variaciones-de-bucles-for" id="toc-variaciones-de-bucles-for" class="nav-link" data-scroll-target="#variaciones-de-bucles-for"><span class="header-section-number">20.3</span> Variaciones de bucles <em>for</em></a>
  <ul class="collapse">
  <li><a href="#modificar-un-objeto-existente" id="toc-modificar-un-objeto-existente" class="nav-link" data-scroll-target="#modificar-un-objeto-existente"><span class="header-section-number">20.3.1</span> Modificar un objeto existente</a></li>
  <li><a href="#patrones-de-bucle" id="toc-patrones-de-bucle" class="nav-link" data-scroll-target="#patrones-de-bucle"><span class="header-section-number">20.3.2</span> Patrones de bucle</a></li>
  <li><a href="#longitud-de-output-desconocida" id="toc-longitud-de-output-desconocida" class="nav-link" data-scroll-target="#longitud-de-output-desconocida"><span class="header-section-number">20.3.3</span> Longitud de <em>output</em> desconocida</a></li>
  <li><a href="#longitud-de-secuencia-desconocida" id="toc-longitud-de-secuencia-desconocida" class="nav-link" data-scroll-target="#longitud-de-secuencia-desconocida"><span class="header-section-number">20.3.4</span> Longitud de secuencia desconocida</a></li>
  <li><a href="#ejercicios-1" id="toc-ejercicios-1" class="nav-link" data-scroll-target="#ejercicios-1"><span class="header-section-number">20.3.5</span> Ejercicios</a></li>
  </ul></li>
  <li><a href="#bucles-for-vs.-funcionales" id="toc-bucles-for-vs.-funcionales" class="nav-link" data-scroll-target="#bucles-for-vs.-funcionales"><span class="header-section-number">20.4</span> Bucles <em>for</em> vs.&nbsp;funcionales</a>
  <ul class="collapse">
  <li><a href="#ejercicios-2" id="toc-ejercicios-2" class="nav-link" data-scroll-target="#ejercicios-2"><span class="header-section-number">20.4.1</span> Ejercicios</a></li>
  </ul></li>
  <li><a href="#las-funciones-map" id="toc-las-funciones-map" class="nav-link" data-scroll-target="#las-funciones-map"><span class="header-section-number">20.5</span> Las funciones <em>map</em></a>
  <ul class="collapse">
  <li><a href="#atajos" id="toc-atajos" class="nav-link" data-scroll-target="#atajos"><span class="header-section-number">20.5.1</span> Atajos</a></li>
  <li><a href="#r-base" id="toc-r-base" class="nav-link" data-scroll-target="#r-base"><span class="header-section-number">20.5.2</span> R Base</a></li>
  <li><a href="#ejercicios-3" id="toc-ejercicios-3" class="nav-link" data-scroll-target="#ejercicios-3"><span class="header-section-number">20.5.3</span> Ejercicios</a></li>
  </ul></li>
  <li><a href="#manejando-los-errores" id="toc-manejando-los-errores" class="nav-link" data-scroll-target="#manejando-los-errores"><span class="header-section-number">20.6</span> Manejando los errores</a></li>
  <li><a href="#usar-map-sobre-múltiples-argumentos" id="toc-usar-map-sobre-múltiples-argumentos" class="nav-link" data-scroll-target="#usar-map-sobre-múltiples-argumentos"><span class="header-section-number">20.7</span> Usar <em>map</em> sobre múltiples argumentos</a>
  <ul class="collapse">
  <li><a href="#invocando-distintas-funciones" id="toc-invocando-distintas-funciones" class="nav-link" data-scroll-target="#invocando-distintas-funciones"><span class="header-section-number">20.7.1</span> Invocando distintas funciones</a></li>
  </ul></li>
  <li><a href="#walk" id="toc-walk" class="nav-link" data-scroll-target="#walk"><span class="header-section-number">20.8</span> Walk</a></li>
  <li><a href="#otros-patrones-para-los-bucles-for" id="toc-otros-patrones-para-los-bucles-for" class="nav-link" data-scroll-target="#otros-patrones-para-los-bucles-for"><span class="header-section-number">20.9</span> Otros patrones para los bucles <em>for</em></a>
  <ul class="collapse">
  <li><a href="#funciones-predicativas" id="toc-funciones-predicativas" class="nav-link" data-scroll-target="#funciones-predicativas"><span class="header-section-number">20.9.1</span> Funciones predicativas</a></li>
  <li><a href="#reducir-y-acumular" id="toc-reducir-y-acumular" class="nav-link" data-scroll-target="#reducir-y-acumular"><span class="header-section-number">20.9.2</span> Reducir y acumular</a></li>
  <li><a href="#ejercicios-4" id="toc-ejercicios-4" class="nav-link" data-scroll-target="#ejercicios-4"><span class="header-section-number">20.9.3</span> Ejercicios</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Iteración</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducción" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">20.1</span> Introducción</h2>
<p>En [funciones], hablamos sobre la importancia de reducir la duplicación en el código creando funciones, en lugar de copiar y pegar. Reducir la duplicación de código tiene tres beneficios principales:</p>
<ol type="1">
<li><p>Es más fácil ver el objetivo de tu código; lo diferente llama más atención a la vista que aquello que permanece igual.</p></li>
<li><p>Es más sencillo responder a cambios en los requerimientos. A medida que tus necesidades cambian, solo necesitarás realizar cambios en un lugar, en vez de recordar cambiar en cada lugar donde copiaste y pegaste el código.</p></li>
<li><p>Es probable que tengas menos errores porque cada línea de código es utilizada en más lugares.</p></li>
</ol>
<p>Una herramienta para reducir la duplicación de código son las funciones, que reducen dicha duplicación al identificar patrones repetidos de código y extraerlos en piezas independientes que pueden reutilizarse y actualizarse fácilmente. Otra herramienta para reducir la duplicación es la <strong>iteración</strong>, que te ayuda cuando necesitas hacer la misma tarea con múltiples entradas: repetir la misma operación en diferentes columnas o en diferentes conjuntos de datos. En este capítulo aprenderás sobre dos paradigmas de iteración importantes: la programación imperativa y la programación funcional. Por el lado imperativo, tienes herramientas como <em>for loops</em> y <em>while loops</em>, que son un gran lugar para comenzar porque hacen que la iteración sea muy explícita, por lo que es obvio qué está pasando. Sin embargo, los bucles <em>for</em> son bastante detallados y requieren bastante código que se duplica para cada bucle. La programación funcional (PF) ofrece herramientas para extraer este código duplicado, por lo que cada patrón común de bucle obtiene su propia función. Una vez que domines el vocabulario de PF, podrás resolver muchos problemas comunes de iteración con menos código, mayor facilidad y menos errores.</p>
<section id="prerrequisitos" class="level3" data-number="20.1.1">
<h3 data-number="20.1.1" class="anchored" data-anchor-id="prerrequisitos"><span class="header-section-number">20.1.1</span> Prerrequisitos</h3>
<p>Una vez que hayas dominado los bucles <em>for</em> proporcionados por R base, aprenderás algunas de las potentes herramientas de programación proporcionadas por <strong>purrr</strong>, uno de los paquetes principales de <em>tidyverse</em>.</p>
</section>
</section>
<section id="bucles-for" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="bucles-for"><span class="header-section-number">20.2</span> Bucles <em>for</em></h2>
<p>Imagina que tenemos este simple <em>tibble</em>:</p>
<p>Queremos calcular la mediana de cada columna. <em>Podrías hacerlo</em> copiando y pegando el siguiente código:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1502829</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09377703</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02390855</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.03339542</code></pre>
</div>
</div>
<p>Pero eso rompe nuestra regla de oro: nunca copiar y pegar más de dos veces. En cambio, podríamos usar un bucle <em>for</em>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.15028286  0.09377703  0.02390855 -0.03339542</code></pre>
</div>
</div>
<p>Cada bucle tiene tres componentes:</p>
<ol type="1">
<li><p><strong>output</strong>: <code>output &lt;- vector("double", length(x))</code>. Antes de comenzar el bucle, siempre debes asignar suficiente espacio para la salida. Esto es muy importante para la eficiencia: si aumentas el bucle <em>for</em> en cada iteración usando, por ejemplo, <code>c ()</code> , el bucle <em>for</em> será muy lento.</p>
<p>Una forma general de crear un vector vacío de longitud dada es la función <code>vector()</code>. Tiene dos argumentos: el tipo de vector (<em>“logical”</em>, <em>“integer”</em>, <em>“double”</em>, <em>“character”</em>, etc) y su longitud.</p></li>
<li><p>La <strong>secuencia</strong>: <code>i in seq_along (df)</code>. Este código determina sobre qué iterar: cada ejecución del bucle <em>for</em> asignará a <code>i</code> un valor diferente de <code>seq_along (df)</code>. Es útil pensar en <code>i</code> como un pronombre, como “eso”.</p>
<p>Es posible que no hayas visto <code>seq_along ()</code> con anterioridad. Es una versión segura de la más familiar <code>1:length(l)</code>, con una diferencia importante: si se tiene un vector de longitud cero, <code>seq_along ()</code> hace lo correcto:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 0</code></pre>
</div>
</div>
<p>Probablemente no vas a crear un vector de longitud cero deliberadamente, pero es fácil crearlos accidentalmente. Si usamos <code>1: length (x)</code> en lugar de <code>seq_along (x)</code>, es posible que obtengamos un mensaje de error confuso.</p></li>
<li><p>El <strong>cuerpo</strong>: <code>output[[i]] &lt;- median(df[[i]])</code>. Este es el código que hace el trabajo. Se ejecuta repetidamente, con un valor diferente para <code>i</code> cada vez. La primera iteración ejecutará <code>output[[1]] &lt;- median(df[[1]])</code>, la segunda ejecutará <code>output [[2]] &lt;- median (df [[2]])</code>, y así sucesivamente.</p></li>
</ol>
<p>¡Eso es todo lo que hay para el bucle <em>for</em>! Ahora es un buen momento para practicar creando algunos bucles <em>for</em> básicos (y no tan básicos) usando los ejercicios que se encuentran a continuación. Luego avanzaremos en algunas variaciones de este bucle que te ayudarán a resolver otros problemas que surgirán en la práctica.</p>
<section id="ejercicios" class="level3" data-number="20.2.1">
<h3 data-number="20.2.1" class="anchored" data-anchor-id="ejercicios"><span class="header-section-number">20.2.1</span> Ejercicios</h3>
<ol type="1">
<li><p>Escribe bucles <em>for</em> para:</p>
<ol type="1">
<li>Calcular la media de cada columna en <code>datos::mtautos</code>.</li>
<li>Determinar el tipo de cada columna en <code>datos::vuelos</code>.</li>
<li>Calcular el número de valores únicos en cada columna de <code>datos::flores</code>.</li>
<li>Generar diez normales aleatorias de distribuciones con medias -10, 0, 10 y 100.</li>
</ol>
<p>Piensa en el resultado, la secuencia y el cuerpo <strong>antes</strong> de empezar a escribir el bucle.</p></li>
<li><p>Elimina el bucle <em>for</em> en cada uno de los siguientes ejemplos aprovechando alguna función existente que trabaje con vectores:</p></li>
<li><p>Combina tus habilidades para escribir funciones y bucles <em>for</em>:</p>
<ol type="1">
<li><p>Escribe un bucle <em>for</em> que imprima (<em><code>prints()</code></em>) la letra de la canción de niños “Cinco ranitas verdes” (u otra).</p></li>
<li><p>Convierte la canción infantil “Cinco monitos saltaban en la cama” en una función. Generalizar a cualquier cantidad de monitos en cualquier estructura para dormir.</p></li>
<li><p>Convierte la canción “99 botellas de cerveza en la pared” en una función. Generalizar a cualquier cantidad, de cualquier tipo de recipiente que contenga cualquier líquido sobre cualquier superficie.</p></li>
</ol></li>
<li><p>Es común ver bucles <em>for</em> que no preasignan el output y en su lugar aumentan la longitud de un vector en cada paso:</p>
<p>¿Cómo afecta esto el rendimiento? Diseña y ejecuta un experimento.</p></li>
</ol>
</section>
</section>
<section id="variaciones-de-bucles-for" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="variaciones-de-bucles-for"><span class="header-section-number">20.3</span> Variaciones de bucles <em>for</em></h2>
<p>Una vez que tienes el bucle <em>for</em> básico en tu haber, hay algunas variaciones que debes tener en cuenta. Estas variaciones son importantes independientemente de cómo hagas la iteración, así que no te olvides de ellas una vez que hayas dominado las técnicas de programación funcional (PF) que aprenderás en la próxima sección.</p>
<p>Hay cuatro variaciones del bucle <em>for</em> básico:</p>
<ol type="1">
<li>Modificar un objeto existente, en lugar de crear un nuevo objeto.</li>
<li>Iterar sobre nombres o valores, en lugar de índices.</li>
<li>Manejar outputs de longitud desconocida.</li>
<li>Manejar secuencias de longitud desconocida.</li>
</ol>
<section id="modificar-un-objeto-existente" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="modificar-un-objeto-existente"><span class="header-section-number">20.3.1</span> Modificar un objeto existente</h3>
<p>Algunas veces querrás usar un bucle <em>for</em> para modificar un objeto existente. Por ejemplo, recuerda el desafío que teníamos en el capítulo sobre [funciones]. Queríamos reescalar cada columna en un <em>data frame</em>:</p>
<p>Para resolver esto con un bucle <em>for</em>, volvamos a pensar en los tres componentes:</p>
<ol type="1">
<li><p><strong>Output</strong>: ya tenemos el <em>output</em> — ¡es lo mismo que la entrada!</p></li>
<li><p><strong>Secuencia</strong>: podemos pensar en un <em>data frame</em> como una lista de columnas, por lo que podemos iterar sobre cada columna con <code>seq_along (df)</code>.</p></li>
<li><p><strong>Cuerpo</strong>: aplicar <code>rescale01 ()</code>.</p></li>
</ol>
<p>Esto nos da:</p>
<p>Por lo general, se modificará una lista o un <em>data frame</em> con este tipo de bucle, así que recuerda utilizar <code>[[</code> y no <code>[</code>. Te habrás fijado que usamos <code>[[</code> en todos nuestros bucles <em>for</em>: creemos que es mejor usar <code>[[</code> incluso para vectores atómicos porque deja en claro que queremos trabajar con un solo elemento.</p>
</section>
<section id="patrones-de-bucle" class="level3" data-number="20.3.2">
<h3 data-number="20.3.2" class="anchored" data-anchor-id="patrones-de-bucle"><span class="header-section-number">20.3.2</span> Patrones de bucle</h3>
<p>Hay tres formas básicas de hacer un bucle sobre un vector. Hasta ahora hemos visto la más general: iterar sobre los índices numéricos con <code>for (i in seq_along (xs))</code>, y extraer el valor con <code>x [[i]]</code>. Hay otras dos formas:</p>
<ol type="1">
<li><p>Iterar sobre los elementos: <code>for (x in xs)</code>. Esta forma es la más útil si solo te preocupas por los efectos secundarios, como graficar o grabar un archivo, porque es difícil almacenar el output de forma eficiente.</p></li>
<li><p>Iterar sobre los nombres: <code>for (nm in names(xs))</code>. Esto te entrega el nombre, que se puede usar para acceder al valor con <code>x [[nm]]</code>. Esto es útil si queremos utilizar el nombre en el título de un gráfico o en el nombre de un archivo. Si estás creando un output con nombre, asegúrate de nombrar el vector de resultados de esta manera:</p></li>
<li><p>Iterar sobre los índices numéricos es la forma más general, porque dada la posición se puede extraer tanto el nombre como el valor:</p></li>
</ol>
</section>
<section id="longitud-de-output-desconocida" class="level3" data-number="20.3.3">
<h3 data-number="20.3.3" class="anchored" data-anchor-id="longitud-de-output-desconocida"><span class="header-section-number">20.3.3</span> Longitud de <em>output</em> desconocida</h3>
<p>Es posible que algunas veces no sepas el tamaño que tendrá el output. Por ejemplo, imagina que quieres simular algunos vectores aleatorios de longitudes aleatorias. Podrías tener la tentación de resolver este problema haciendo crecer el vector progresivamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> num [1:70] -0.993 -1.251 0.444 1.683 0.836 ...</code></pre>
</div>
</div>
<p>Pero esto no es muy eficiente porque en cada iteración, R tiene que copiar todos los datos de las iteraciones anteriores. En términos técnicos, obtienes un comportamiento “cuadrático” (<span class="math inline">\(O(n^2)\)</span>), lo que significa que un bucle que tiene tres veces más elementos tomaría nueve (<span class="math inline">\(3^2\)</span>) veces más tiempo en ejecutarse.</p>
<p>Una mejor solución es guardar los resultados en una lista y luego combinarlos en un solo vector una vez que se complete el ciclo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ : num [1:91] -0.072 -0.0614 0.0518 0.7394 0.0771 ...
 $ : num [1:22] 0.439 -0.783 -0.883 -0.447 0.914 ...
 $ : num [1:84] 2.9477 2.2724 1.1733 4.8428 -0.0536 ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:197] -0.072 -0.0614 0.0518 0.7394 0.0771 ...</code></pre>
</div>
</div>
<p>Aquí usamos <code>unlist ()</code> (<em>deslistar</em> en inglés) para aplanar una lista de vectores en un solo vector. Una opción más estricta es usar <code>purrr :: flatten_dbl ()</code> (<em>aplanar dobles</em>) — arrojará un error si el input no es una lista de dobles.</p>
<p>Este patrón ocurre también en otros lugares:</p>
<ol type="1">
<li><p>Podrías estar generando una cadena larga. En lugar de pegar (<code>paste ()</code>) cada iteración con la anterior, guarda el output en un vector de caracteres y luego combina ese vector en una cadena con <code>paste(output, collapse = "")</code>.</p></li>
<li><p>Podrías estar generando un <em>data frame</em> grande. En lugar de enlazar (<code>rbind ()</code>) secuencialmente en cada iteración, guarda el resultado en una lista y luego utiliza <code>dplyr::bind_rows(output)</code> para combinar el output en un solo <em>data frame</em>.</p></li>
</ol>
<p>Cuidado con este patrón. Cuando lo veas, cambia a un objeto de resultado más complejo y luego combínalo en un solo paso al final.</p>
</section>
<section id="longitud-de-secuencia-desconocida" class="level3" data-number="20.3.4">
<h3 data-number="20.3.4" class="anchored" data-anchor-id="longitud-de-secuencia-desconocida"><span class="header-section-number">20.3.4</span> Longitud de secuencia desconocida</h3>
<p>A veces ni siquiera sabemos cuánto tiene que durar la secuencia de entrada. Esto es común cuando se hacen simulaciones. Por ejemplo, es posible que se quiera realizar un bucle hasta que se obtengan tres caras seguidas. No podemos hacer ese tipo de iteración con un bucle <em>for</em>. En su lugar, podemos utilizar un bucle <em>while</em> (<em>mientras</em>, en inglés). Un bucle <em>while</em> es más simple que un bucle <em>for</em> porque solo tiene dos componentes, una condición y un cuerpo:</p>
<p>Un bucle <em>while</em> también es más general que un bucle <em>for</em>, porque podemos reescribir este último como un bucle <em>while</em>, pero no podemos reescribir todos los bucles <em>while</em> bucles <em>for</em>:</p>
<p>Así es como podríamos usar un bucle <em>while</em> para encontrar cuántos intentos se necesitan para obtener tres caras seguidas:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>Mencionamos los bucles <em>while</em> brevemente, porque casi nunca los usamos. Se utilizan con mayor frecuencia para hacer simulaciones, un tema que está fuera del alcance de este libro. Sin embargo, es bueno saber que existen en caso que nos encontremos con problemas en los que el número de iteraciones no se conoce de antemano.</p>
</section>
<section id="ejercicios-1" class="level3" data-number="20.3.5">
<h3 data-number="20.3.5" class="anchored" data-anchor-id="ejercicios-1"><span class="header-section-number">20.3.5</span> Ejercicios</h3>
<ol type="1">
<li><p>Imagina que tienes un directorio lleno de archivos CSV que quieres importar. Tienes sus ubicaciones en un vector, <code>files &lt;- dir("data/", pattern = "\\.csv$", full.names = TRUE)</code>, y ahora quieres leer cada uno con <code>read_csv()</code>. Escribe un bucle <em>for</em> que los cargue en un solo <em>data frame</em>.</p></li>
<li><p>¿Qué pasa si utilizamos <code>for (nm in names(x))</code> y <code>x</code> no tiene nombres (<em>names</em>)? ¿Qué pasa si solo algunos elementos están nombrados? ¿Qué pasa si los nombres no son únicos?</p></li>
<li><p>Escribe una función que imprima el promedio de cada columna numérica en un <em>data frame</em>, junto con su nombre. Por ejemplo, <code>mostrar_promedio(flores)</code> debe imprimir:</p>
<p>(Desafío adicional: ¿qué función utilizamos para asegurarnos que los números queden alineados a pesar que los nombres de las variables tienen diferentes longitudes?)</p></li>
<li><p>¿Qué hace este código? ¿Cómo funciona?</p></li>
</ol>
</section>
</section>
<section id="bucles-for-vs.-funcionales" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="bucles-for-vs.-funcionales"><span class="header-section-number">20.4</span> Bucles <em>for</em> vs.&nbsp;funcionales</h2>
<p>Los bucles <em>for</em> no son tan importantes en R como en otros lenguajes porque R es un lenguaje de programación funcional. Esto significa que es posible envolver los bucles en una función y llamar a esa función en lugar de usar el bucle <em>for</em> directamente.</p>
<p>Para ver por qué esto es importante, consideremos (nuevamente) este <em>data frame</em> simple:</p>
<p>Imagina que quieres calcular la media de cada columna. Podríamos hacer eso con un bucle <em>for</em>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.2777127  0.1941377  0.1349587 -0.5742073</code></pre>
</div>
</div>
<p>Como te das cuenta que vas querer calcular los promedios de cada columna con bastante frecuencia, extraer el bucle en una función:</p>
<p>Pero entonces pensamos que también sería útil poder calcular la mediana y la desviación estándar, así que copiamos y pegamos la función <code>col_media ()</code> y reemplazamos <code>mean ()</code> con <code>median ()</code> y <code>sd ()</code>:</p>
<p>¡Oh oh! Copiaste y pegaste este código dos veces, por lo que es hora de pensar cómo generalizarlo. Ten en cuenta que la mayoría de este código corresponde al texto trillado del bucle <em>for</em>, lo que hace difícil ver la única cosa que es diferente entre las funciones (<code>mean ()</code>, <code>median ()</code>, <code>sd ()</code>).</p>
<p>¿Qué podŕias hacer si ves un conjunto de funciones como esta?:</p>
<p>Por suerte, habrás notado que hay mucha duplicación que puedes extraer con un argumento adicional:</p>
<p>Redujiste la posibilidad de errores (porque ahora tienes 1/3 menos de código) y hiciste más fácil generalizar para situaciones nuevas.</p>
<p>Podemos hacer exactamente lo mismo con <code>col_media ()</code>, <code>col_mediana ()</code> y <code>col_desvest ()</code> agregando un argumento que proporciona la función a aplicar en cada columna:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.08391801  0.27926535  0.31349765 -0.77937147</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.2777127  0.1941377  0.1349587 -0.5742073</code></pre>
</div>
</div>
<p>La idea de pasar una función a otra es extremadamente poderosa y es uno de los comportamientos que hacen de R un lenguaje de programación funcional. Puede que te tome un tiempo comprender la idea, pero vale la pena el esfuerzo. En el resto del capítulo aprenderás y usarás el paquete <strong>purrr</strong>, que proporciona funciones que eliminan la necesidad de muchos de los bucles comunes. La familia de funciones de R base <em>apply</em> (<em>aplicar</em>: <code>apply ()</code>, <code>lapply ()</code>, <code>tapply ()</code>, etc.) resuelve un problema similar; sin embargo, <em>purrr</em> es más consistente y, por lo tanto, es más fácil de aprender.</p>
<p>El objetivo de usar las funciones de <em>purrr</em> en lugar de los bucles es que te permite dividir los desafíos comunes de manipulación de listas en partes independientes:</p>
<ol type="1">
<li><p>¿Cómo puedes resolver el problema para un solo elemento de la lista? Una vez que encuentres la solución, <em>purrr</em> se encargará de generalizarla a cada elemento de la lista.</p></li>
<li><p>Si estás resolviendo un problema complejo, ¿cómo puedes dividirlo en pequeñas etapas que te permitan avanzar paso a paso hacia la solución? Con <strong>purrr</strong> obtienes muchas piezas pequeñas que puedes ensamblar utilizando el <em>pipe</em> (<code>%&gt;%</code>).</p></li>
</ol>
<p>Esta estructura facilita la resolución de nuevos problemas. También hace que sea más fácil entender las soluciones a problemas antiguos cuando relees código que escribiste en el pasado.</p>
<section id="ejercicios-2" class="level3" data-number="20.4.1">
<h3 data-number="20.4.1" class="anchored" data-anchor-id="ejercicios-2"><span class="header-section-number">20.4.1</span> Ejercicios</h3>
<ol type="1">
<li><p>Lee la documentación para <code>apply ()</code>. En el caso 2d, ¿qué dos bucles <em>for</em> generaliza?</p></li>
<li><p>Adapta <code>col_resumen()</code> para que solo se aplique a las columnas numéricas. Podrías querer comenzar con la función <code>is_numeric ()</code> que devuelve un vector lógico que tenga un <em>TRUE</em> por cada columna numérica.</p></li>
</ol>
</section>
</section>
<section id="las-funciones-map" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="las-funciones-map"><span class="header-section-number">20.5</span> Las funciones <em>map</em></h2>
<p>El patrón de iterar sobre un vector, hacer algo con cada elemento y guardar los resultados es tan común que el paquete <strong>purrr</strong> proporciona una familia de funciones que lo hacen por ti. Hay una función para cada tipo de output:</p>
<ul>
<li><code>map ()</code> crea una lista.</li>
<li><code>map_lgl ()</code> crea un vector lógico.</li>
<li><code>map_int ()</code> crea un vector de enteros.</li>
<li><code>map_dbl ()</code> crea un vector de dobles.</li>
<li><code>map_chr ()</code> crea un vector de caracteres.</li>
</ul>
<p>Cada función <code>map</code> (<em>mapa</em>, en español) toma un vector como input, aplica una función a cada elemento y luego devuelve un nuevo vector que tiene la misma longitud (y los mismos nombres) que el input. El tipo de vector está determinado por el sufijo de la función <em>map</em>.</p>
<p>Una vez que domines estas funciones, descubrirás que lleva mucho menos tiempo resolver los problemas de iteración. Sin embargo, nunca debes sentirse mal por usar un bucle <em>for</em> en lugar de una función <em>map</em>. Las funciones <em>map</em> son un nivel superior de abstracción y puede llevar mucho tiempo entender cómo funcionan. Lo importante es que resuelvas el problema en el que estás trabajando, no que escribas el código más conciso y elegante (¡aunque eso es definitivamente algo a lo que aspirar!).</p>
<p>Algunas personas te dirán que evites los bucles <em>for</em> porque son lentos. ¡Están equivocados! (Bueno, al menos están bastante desactualizados, ya que los bucles <em>for</em> han dejado de ser lentos desde hace muchos años). Los principales beneficios de usar funciones como <code>map ()</code> no es la velocidad, sino la claridad: hacen que tu código sea más fácil de escribir y leer.</p>
<p>Podemos usar estas funciones para realizar los mismos cálculos que el último bucle <em>for</em>. Esas funciones de resumen devolvían valores decimales, por lo que necesitamos usar <code>map_dbl ()</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         a          b          c          d 
 0.2777127  0.1941377  0.1349587 -0.5742073 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          a           b           c           d 
 0.08391801  0.27926535  0.31349765 -0.77937147 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        a         b         c         d 
0.8769214 0.9035574 0.9202586 1.0533656 </code></pre>
</div>
</div>
<p>Comparado con el uso de un bucle for, el foco está en la operación que se está realizando (es decir, <code>mean ()</code>, <code>median ()</code>, <code>sd ()</code>), y no en llevar la cuenta de las acciones requeridas para recorrer cada elemento y almacenar el output. Esto es aún más evidente si usamos el <em>pipe</em>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         a          b          c          d 
 0.2777127  0.1941377  0.1349587 -0.5742073 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          a           b           c           d 
 0.08391801  0.27926535  0.31349765 -0.77937147 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        a         b         c         d 
0.8769214 0.9035574 0.9202586 1.0533656 </code></pre>
</div>
</div>
<p>Existen algunas diferencias entre <code>map _ * ()</code> y <code>col_resumen()</code>:</p>
<ul>
<li><p>Todas las funciones de purrr están implementadas en C. Esto las hace más rápidas a expensas de la legibilidad.</p></li>
<li><p>El segundo argumento, <code>.f</code>, la función a aplicar, puede ser una fórmula, un vector de caracteres o un vector de enteros. Aprenderás acerca de estos atajos útiles en la siguiente sección.</p></li>
<li><p><code>map_*()</code> usa … ([dot dot dot] - punto punto punto) para pasar los argumentos adicionales a <code>.f</code> cada vez que se llama:</p>
<p>::: {.cell} ::: {.cell-output .cell-output-stdout} <code>a           b           c           d     0.08391801  0.27926535  0.31349765 -0.77937147</code> ::: :::</p></li>
<li><p>Las funciones <em>map</em> también preservan los nombres:</p>
<p>::: {.cell} ::: {.cell-output .cell-output-stdout} <code>x y    3 2</code> ::: :::</p></li>
</ul>
<section id="atajos" class="level3" data-number="20.5.1">
<h3 data-number="20.5.1" class="anchored" data-anchor-id="atajos"><span class="header-section-number">20.5.1</span> Atajos</h3>
<p>Existen algunos atajos que puedes usar con <code>.f</code> para ahorrar algo de tipeo Imagina que quieres ajustar un modelo lineal a cada grupo en un conjunto de datos. El siguiente ejemplo de juguete divide el dataset <code>mtautos</code> en tres partes (una para cada valor de cilindro) y ajusta el mismo modelo lineal a cada parte:</p>
<p>La sintaxis para crear una función anónima en R es bastante verbosa, por lo que purrr provee un atajo conveniente: una fórmula unilateral.</p>
<p>Hemos usado <code>.</code> como pronombre: se refiere al elemento actual de la lista (del mismo modo que <code>i</code> se refiere al índice actual en el loop for). <code>.x</code> corresponde al argumento de una función anónima.</p>
<p>Cuando examinas múltiples modelos, puedes querer extraer un estadístico resumen como lo es <span class="math inline">\(R^2\)</span>. Para hacer eso primero necesitas correr <code>summary()</code> y luego extraer la componente <code>r.squared</code> (R-cuadrado). Podríamos hacerlo usando un atajo para las funciones anónimas:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        4         6         8 
0.5086326 0.4645102 0.4229655 </code></pre>
</div>
</div>
<p>Sin embargo, extraer componentes con nombres es una operación común, por lo que purrr provee un atajo aún más corto: puedes usar una cadena de caracteres (o <em>string</em>).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        4         6         8 
0.5086326 0.4645102 0.4229655 </code></pre>
</div>
</div>
<p>También puedes usar un entero para seleccionar elementos de acuerdo a su posición:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 5 8</code></pre>
</div>
</div>
</section>
<section id="r-base" class="level3" data-number="20.5.2">
<h3 data-number="20.5.2" class="anchored" data-anchor-id="r-base"><span class="header-section-number">20.5.2</span> R Base</h3>
<p>Si la familia de funciones <em>apply</em> en R base te son familiares, podrás haber notado algunas similitudes con las funciones de purrr:</p>
<ul>
<li><p><code>lapply()</code> es básicamente idéntica a <code>map()</code>, excepto que <code>map()</code> es consistente con todas las otras funciones de purrr y puedes usar atajos para <code>.f</code>.</p></li>
<li><p><code>sapply()</code> es un envoltorio (<em>wrapper</em>) de <code>lapply()</code> que automáticamente simplifica el output. Esto es úti lpara el trabajo interactivo pero es problemático en una función, ya que nunca sabrás qué tipo de output vas a obtener:</p>
<p>::: {.cell} ::: {.cell-output .cell-output-stdout} <code>List of 3    $ : num 0.91    $ : num [1:2] 0.9 0.94    $ : num(0)</code> :::</p>
<p>::: {.cell-output .cell-output-stdout} <code>num [1:3] 0.99 0.93 0.87</code> ::: :::</p></li>
<li><p><code>vapply()</code> es una alternativa más segura a <code>sapply()</code> porque debes ingresar un argumento adicional que define el tipo de output. El único problema con <code>vapply()</code> es es que requiere mucha escritura: <code>vapply(df, is.numeric, logical(1))</code> es equivalente a <code>map_lgl(df, is.numeric)</code>. Una ventaja de <code>vapply()</code> sobre las funciones <em>map</em> de purrr es que también puede generar matrices — las funciones <em>map</em> solo generan vectores.</p></li>
</ul>
<p>Aquí nos enfocamos en las funciones de purrr, ya que proveen nombres y argumentos consistentes, atajos útiles y en el futuro proveerán paralelización simple y barras de progreso.</p>
</section>
<section id="ejercicios-3" class="level3" data-number="20.5.3">
<h3 data-number="20.5.3" class="anchored" data-anchor-id="ejercicios-3"><span class="header-section-number">20.5.3</span> Ejercicios</h3>
<ol type="1">
<li><p>Escribe un código que use una de las funciones de map para:</p>
<ol type="1">
<li>Calcular la media de cada columna en <code>datos::mautos</code>.</li>
<li>Obtener de qué tipo es cada columna en <code>datos::vuelos</code>.</li>
<li>Calcular la cantidad de valores únicos en cada columna de <code>datos::flores</code>.</li>
<li>Generar diez normales aleatorias de distribuciones con medias -10, 0, 10 y 100.</li>
</ol></li>
<li><p>¿Cómo puedes crear un vector tal que para cada columna en un data frame indique si corresponde o no a un factor?</p></li>
<li><p>¿Qué ocurre si usas las funciones <em>map</em> en vectores que no son listas? ¿Qué hace <code>map(1:5, runif)</code>? ¿Por qué?</p></li>
<li><p>¿Qué hace <code>map(-2:2, rnorm, n = 5)</code>? ¿Por qué? ¿Qué hace <code>map_dbl(-2:2, rnorm, n = 5)</code>? ¿Por qué?</p></li>
<li><p>Reescribe <code>map(x, function(df) lm(mpg ~ wt, data = df))</code> para eliminar todas las funciones anónimas.</p></li>
</ol>
</section>
</section>
<section id="manejando-los-errores" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="manejando-los-errores"><span class="header-section-number">20.6</span> Manejando los errores</h2>
<p>Cuando usas las funciones <em>map</em> para repetir muchas operaciones, la probabilidad de que una de estas falle es mucho más alta. Cuando esto ocurre, obtendrás un mensaje de error y no una salida. Esto es molesto: ¿por qué un error evita que accedas a todo lo que sí funcionó? ¿Cómo puedes asegurarte de que una manzana podrida no arruine todo el barril?</p>
<p>En esta sección aprenderás a manejar estas situaciones con una nueva función: <code>safely()</code> (<em>de forma segura</em>, en inglés). <code>safely()</code> es un adverbio: toma una función (un verbo) y entrega una versión modificada. En este caso, la función modificada nunca lanzará un error. En cambio, siempre devolverá una lista de dos elementos:</p>
<ol type="1">
<li><p><code>result</code> es el resultado original. Si hubo un error, aparecerá como <code>NULL</code>,</p></li>
<li><p><code>error</code> es un objeto de error. Si la operación fue exitosa, será <code>NULL</code>.</p></li>
</ol>
<p>(Puede que estés familiarizado con la función <code>try()</code> (<em>intentar</em>) de R base. Es similar, pero dado que a veces entrega el resultado original y a veces un objeto de error, es más díficil para trabajar.)</p>
<p>Veamos esto con un ejemplo simple: <code>log()</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ result: num 2.3
 $ error : NULL</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ result: NULL
 $ error :List of 2
  ..$ message: chr "non-numeric argument to mathematical function"
  ..$ call   : language .Primitive("log")(x, base)
  ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition"</code></pre>
</div>
</div>
<p>Cuando la función es exitosa, el elemento <code>result</code> contiene el resultado y el elemento <code>error</code> es <code>NULL</code>. Cuando la función falla, el elemento <code>result</code> es <code>NULL</code> y el elemento <code>error</code> contiene un objeto de error.</p>
<p><code>safely()</code> está diseñada para funcionar con <em>map</em>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ :List of 2
  ..$ result: num 0
  ..$ error : NULL
 $ :List of 2
  ..$ result: num 2.3
  ..$ error : NULL
 $ :List of 2
  ..$ result: NULL
  ..$ error :List of 2
  .. ..$ message: chr "non-numeric argument to mathematical function"
  .. ..$ call   : language .Primitive("log")(x, base)
  .. ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition"</code></pre>
</div>
</div>
<p>Esto sería más fácil de trabajar si tuvieramos dos listas: una con todos los errores y otra con todas las salidas, Esto es fácil de obtener con <code>purrr::transpose()</code> (<em>transponer</em>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ result:List of 3
  ..$ : num 0
  ..$ : num 2.3
  ..$ : NULL
 $ error :List of 3
  ..$ : NULL
  ..$ : NULL
  ..$ :List of 2
  .. ..$ message: chr "non-numeric argument to mathematical function"
  .. ..$ call   : language .Primitive("log")(x, base)
  .. ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition"</code></pre>
</div>
</div>
<p>Queda a tu criterio cómo manejar los errores, pero típicamente puedes mirar los valores de <code>x</code> donde <code>y</code> es un error, o trabajar con los valores que <code>y</code> que están ok:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] "a"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000000 2.302585</code></pre>
</div>
</div>
<p>Purrr provee otros dos adverbios útiles:</p>
<ul>
<li><p>Al igual que <code>safely()</code>, <code>possibly()</code> (<em>posiblemente</em>) siempre tendrá éxito. Es más simple que <code>safely()</code>, ya que le das un valor por defecto para devolver cuando haya un error.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000000 2.302585       NA</code></pre>
</div>
</div></li>
<li><p><code>quietly()</code> (<em>silenciosamente</em>) tiene un rol similar a <code>safely()</code>, pero en lugar de capturar los errores, captura el output impreso, los mensajes y las advertencias:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ :List of 4
  ..$ result  : num 0
  ..$ output  : chr ""
  ..$ warnings: chr(0) 
  ..$ messages: chr(0) 
 $ :List of 4
  ..$ result  : num NaN
  ..$ output  : chr ""
  ..$ warnings: chr "NaNs produced"
  ..$ messages: chr(0) </code></pre>
</div>
</div></li>
</ul>
</section>
<section id="usar-map-sobre-múltiples-argumentos" class="level2" data-number="20.7">
<h2 data-number="20.7" class="anchored" data-anchor-id="usar-map-sobre-múltiples-argumentos"><span class="header-section-number">20.7</span> Usar <em>map</em> sobre múltiples argumentos</h2>
<p>Hasta ahora hemos “mapeado” sobre un único input. Pero a menudo tienes multiples inputs relacionados y necesitas iterar sobre ellos en paralelo. Ese es el trabajo de las funciones <code>map2()</code> y <code>pmap()</code>. Por ejemplo, imagina que quieres simular normales aleatorias con distintas medias. Ya sabes hacerlo con <code>map()</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ : num [1:5] 6.77 4.66 3.7 3.34 3.7
 $ : num [1:5] 9.25 9.33 8.61 9.09 8.46
 $ : num [1:5] -3.11 -3.56 -3.48 -2.92 -3.3</code></pre>
</div>
</div>
<p>¿Qué ocurre si también necesitas cambiar la desviación estándar? Una forma de hacerlo sería iterar sobre los índices e indexar en vectores de medias y desviaciones estándar:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ : num [1:5] 3.02 4.83 4.88 5.42 4.85
 $ : num [1:5] 10.1 10.8 4.75 7.99 14.29
 $ : num [1:5] 2.3 8.42 -3.18 7.33 1.47</code></pre>
</div>
</div>
<p>Pero esto oscurece la intención del código. En su lugar podríamos usar <code>map2()</code>, que itera sobre dos vectores en paralelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ : num [1:5] 4.28 6.51 4.78 5.09 4.38
 $ : num [1:5] 9.52 5.49 3.51 16.25 5.1
 $ : num [1:5] -2.33 -12.18 1.98 9.02 4.67</code></pre>
</div>
</div>
<p><code>map2()</code> genera esta serie de llamadas a funciones:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams_w_text_as_path/es/lists-map2.svg" class="img-fluid"></p>
</div>
</div>
<p>Observa que los argumentos que varían para cada llamada van <em>antes</em> de la función; argumentos que son los mismos para cada llamada van <em>después</em>.</p>
<p>Al igual que <code>map()</code>, <code>map2()</code> es un envoltorio en torno a un bucle <em>for</em>:</p>
<p>También te podrás imaginar <code>map3()</code>, <code>map4()</code>, <code>map5()</code>, <code>map6()</code>, etc., pero eso se volvería tedioso rápidamente. En cambio, purrr provee <code>pmap()</code>, que toma una lista de argumentos. Puedes usar eso si quieres cambiar la media, desviación estándar y el número de muestras:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ : num 2.56
 $ : num [1:3] -3.03 7.09 13.95
 $ : num [1:5] 5.45 -1.63 7.12 -4.03 -4.21</code></pre>
</div>
</div>
<p>Esto se ve así:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams_w_text_as_path/es/lists-pmap-unnamed.svg" class="img-fluid"></p>
</div>
</div>
<p>Si no nombras todos los elementos de la lista, <code>pmap()</code> usará una coincidencia posicional al llamar la función. Esto es un poco frágil y hace el código más difícil de leer, por lo que es mejor nombrar los argumentos:</p>
<p>Esto genera llamadas más largas, pero más seguras:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams_w_text_as_path/es/lists-pmap-named.svg" class="img-fluid"></p>
</div>
</div>
<p>Dado que los argumentos son todos del mismo largo, tiene sentido almacenarlos en un data frame:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 6.061035

[[2]]
[1] 11.460077  9.192743 15.870863

[[3]]
[1]  -3.333802 -14.671462  21.080138   3.361022   8.338264</code></pre>
</div>
</div>
<p>Utilizar un data frame cuando tu código se vuelve complicado nos parece una buena aproximación, ya que asegura que cada columna tenga nombre y el mismo largo que las demás columnas.</p>
<section id="invocando-distintas-funciones" class="level3" data-number="20.7.1">
<h3 data-number="20.7.1" class="anchored" data-anchor-id="invocando-distintas-funciones"><span class="header-section-number">20.7.1</span> Invocando distintas funciones</h3>
<p>Existe un paso adicional en términos de complejidad. Así como cambias los argumentos de la función también puedes cambiar la función misma:</p>
<p>Para manejar este caso, puedes usar <code>invoke_map()</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ : num [1:5] 0.227 -0.633 0.439 0.325 -0.38
 $ : num [1:5] 7.903 0.395 1.718 -12.758 -1.786
 $ : int [1:5] 8 10 13 9 11</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams_w_text_as_path/es/lists-invoke.svg" class="img-fluid"></p>
</div>
</div>
<p>El primer argumento es una lista de funciones o un vector de caracteres con nombres de funciones. El segundo argumento es una lista de listas que indica los argumentos que cambian en cada función. Los argumentos subsecuentes pasan a cada función.</p>
<p>Nuevamente, puedes usar <code>tribble()</code> para hacer la creación de tuplas coincidentes un poco más fácil:</p>
</section>
</section>
<section id="walk" class="level2" data-number="20.8">
<h2 data-number="20.8" class="anchored" data-anchor-id="walk"><span class="header-section-number">20.8</span> Walk</h2>
<p><em>Walk</em> es una alternativa a <em>map</em> que puedes usar cuando quieras llamar a una función por sus efectos colaterales, más que por sobre el valor que devuelve. Típicamente hacemos esto cuando queremos mostrar la salida en pantalla o guardar archivos en el disco. Lo importante es la acción, no el valor resultante. Aquí hay un ejemplo simple:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1
[1] "a"
[1] 3</code></pre>
</div>
</div>
<p>Generalmente <code>walk()</code> no es tan útil si se compara con <code>walk2()</code> o <code>pwalk()</code>. Por ejemplo, si tienes una lista de gráficos y un vector con nombres de archivos, puedes usar <code>pwalk()</code> para guardar cada archivo en su ubicación correspondiente en el disco:</p>
<p><code>walk()</code>, <code>walk2()</code> y <code>pwalk()</code> devuelven de forma invisible <code>.</code>, el primer argumento. Esto las hace adecuadas para usar dentro de cadenas de pipes.</p>
</section>
<section id="otros-patrones-para-los-bucles-for" class="level2" data-number="20.9">
<h2 data-number="20.9" class="anchored" data-anchor-id="otros-patrones-para-los-bucles-for"><span class="header-section-number">20.9</span> Otros patrones para los bucles <em>for</em></h2>
<p>Purr entrega algunas funciones que resumen otros tipos de bucles <em>for</em>. Si bien los usarás de manera menos frecuente que las funciones map, es útil conocerlas. El objetivo aquí es ilustrar brevemente cada una, con la esperanza de que vengan a tu mente en el futuro cuando veas un problema similar. Luego puedes consultar la documentación para más detalles.</p>
<section id="funciones-predicativas" class="level3" data-number="20.9.1">
<h3 data-number="20.9.1" class="anchored" data-anchor-id="funciones-predicativas"><span class="header-section-number">20.9.1</span> Funciones predicativas</h3>
<p>Algunas funciones trabajan con funciones <em>predicativas</em> que entregan un único valor <code>TRUE</code> o <code>FALSE</code>.</p>
<p><code>keep()</code> y <code>discard()</code> mantienen los elementos de la entrada donde el predicado es <code>TRUE</code> o <code>FALSE</code>, respectivamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   150 obs. of  1 variable:
 $ Especie: Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   150 obs. of  4 variables:
 $ Largo.Sepalo: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Ancho.Sepalo: num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Largo.Petalo: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Ancho.Petalo: num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...</code></pre>
</div>
</div>
<p><code>some()</code> y <code>every()</code> determinan si el predicado es verdadero para todos o para algunos de los elementos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p><code>detect()</code> encuentra el primer elemento donde el predicado es verdadero; <code>detect_index()</code> entrega su posición.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1]  7 10  2  9  8  3  4  5  6  1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p><code>head_while()</code> y <code>tail_while()</code> toman elementos al inicio y final de un vector cuando el predicado es verdadero:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1]  7 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
</section>
<section id="reducir-y-acumular" class="level3" data-number="20.9.2">
<h3 data-number="20.9.2" class="anchored" data-anchor-id="reducir-y-acumular"><span class="header-section-number">20.9.2</span> Reducir y acumular</h3>
<p>A veces tendrás una lista compleja que quieres reducir a una lista simple aplicando repetidamente una función que reduce un par a un elemento único. Esto es útil si quieres aplicar un verbo de dos tablas de dplyr a múltiples tablas. Por ejemplo, si tienes una lista de data frames, y quieres reducirla a un unico data frame uniendo los elementos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  name    age sex   treatment
  &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    
1 John     30 M     &lt;NA&gt;     
2 Mary     NA F     A        </code></pre>
</div>
</div>
<p>O puedes tener una lista de vectores y quieres encontrar la intersección:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  3 10</code></pre>
</div>
</div>
<p>La función <code>reduce()</code> (<em>reducir</em>) toma una función “binaria” (e.g.&nbsp;una función con dos inputs primarios) y la aplica repetidamente a una lista hasta que quede un solo elemento.</p>
<p><code>accumulate()</code> (<em>acumular</em>) es similar, pero mantiene todos los resultados intermedios. Podría usarse para implementar una suma acumulativa:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1  8  9 10  3  5  7  2  4  6</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1  9 18 28 31 36 43 45 49 55</code></pre>
</div>
</div>
</section>
<section id="ejercicios-4" class="level3" data-number="20.9.3">
<h3 data-number="20.9.3" class="anchored" data-anchor-id="ejercicios-4"><span class="header-section-number">20.9.3</span> Ejercicios</h3>
<ol type="1">
<li><p>Implementa tu propia versión de <code>every()</code> usando un bucle <em>for</em>. Compárala con <code>purrr::every()</code>. ¿Qué hace la versión de purrr que la tuya no?</p></li>
<li><p>Crea una mejora de <code>col_resumen()</code> que aplique una función de resumen a cada columna numérica en un data frame.</p></li>
<li><p>Un posible equivalente de <code>col_resumen()</code> es:</p>
<p>Pero tiene una cantidad de bugs que queda ilustrada con las siguientes entradas:</p>
<p>¿Qué causa los <em>bugs</em>?</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./20-vectors.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Vectores</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./22-model.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Introducción</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>