{
  "hash": "0f59e8d24e0adbeee75c17e1c87be74a",
  "result": {
    "markdown": "# Vectores\n\n## Introducción\n\nHasta ahora este libro se ha enfocado en los tibbles y los paquetes que trabajan con ellos. Pero a medida que empieces a escribir tus propias funciones y a profundizar en R, es necesario que aprendas sobre vectores, esto es, sobre los objetos que están a la base de los tibbles. Si aprendiste R de una manera más tradicional, probablemente ya te hayas familiarizado con los vectores, ya que la mayoría de los recursos sobre R parten con vectores y luego abordan los tibbles. Creemos que es mejor empezar con los tibbles porque resultan útiles de inmediato y luego explorar los componentes que están a la base. \nLos vectores son particularmente importantes, ya que la mayoría de las funciones que escribirás trabajan con ellos. Es posible escribir funciones que trabajen con tibbles (como **ggplot2**, **dplyr** y **tidyr**); sin embargo, las herramientas que necesitas para hacerlo aún son idiosincráticas y no están lo suficientemente maduras. Estamos trabajando en una mejor aproximación (https://github.com/hadley/lazyeval), pero no estará lista a tiempo para la publicación del libro. Incluso aún cuando esté completa, será necesaro que entiendas los vectores: hará que sea más fácil escribir una capa amigable con el usuario encima de ellos.\n\n### Prerrequisitos\n\nEste capítulo se enfoca en las estructuras de datos de R base, por lo que no es esencial cargar ningún paquete. Sin embargo, usaremos un conjunto de funciones del paquete **purrr** para evitar algunas inconsistencias de R base.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n## Vectores básicos\n\nHay dos tipos de vectores:\n\n1.\tVectores **atómicos**, de los cuales existen seis tipos: **lógico**, **entero**, **doble**, **caracter**, **complejo** y **sin procesar** (_raw_). Los vectores de tipo entero y doble son conocidos de manera colectiva como vectores numéricos.\n2.\tLas **listas**, que a veces son denominadas como vectores recursivos debido a que pueden contener otras listas.\n\nLa diferencia principal entre vectores atómicos y listas es que los vectores atómicos son **homogéneos**, mientras las listas pueden ser **heterogéneas**. Existe otro objeto relacionado: `NULL` (nulo). `NULL` es a menudo utilizado para representar la ausencia de un vector (en oposición a `NA` que se utiliza para representar la ausencia de un valor en un vector). `NULL` se comporta típicamente como un vector de longitud 0 (cero). La figura \\@ref(fig:datatypes) resume las interrelaciones.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![La jerarquía de los tipos de vectores en R](diagrams_w_text_as_path/es/data-structures-overview.svg){width=50%}\n:::\n:::\n\n\nCada vector tiene dos propiedades clave:\n\n1. Su __tipo__ (_type_), que puedes determinar con `typeof()` (_tipo de_).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n typeof(letters)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\n typeof(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"integer\"\n```\n:::\n:::\n\n\n2. Su __longitud__ (_length_), que puede determinar con `length()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n x <- list(\"a\", \"b\", 1:10)\n length(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3\n```\n:::\n:::\n\n\nLos vectores pueden contener también metadata adicional arbitraria en forma de atributos. Estos atributos son usados para crear **vectores aumentados**, los que se basan en un comportamiento distinto. Existen tres tipos de vectores aumentados:\n* Los factores (_factors_), construidos sobre la base de vectores de enteros.\n* Las fechas y fechas-hora (_date-times_), construidas a partir de vectores numéricos.\n* Los dataframes y tibbles, construidos a partir de listas.\n\nEste capítulo te introducirá en estos importantes vectores, desde los más simples a los más complicados. Comenzarás con vectores atómicos, luego seguirás con listas y finalizarás con vectores aumentados.\n\n## Tipos importantes de vectores atómicos\n\nLos cuatro tipos más importantes de vectores atómicos son lógico, entero, doble y carácter. Los de tipo _raw_ y complejo son raramente usados durante el análisis de datos, por lo tanto, no discutiremos sobre ellos aquí.\n\n### Lógico\nLos vectores de tipo lógico son el tipo más sencillo de vectores atómicos, ya que solo pueden tomar tres valores posibles: `FALSE`, `TRUE` y `NA`. Los vectores lógicos son construidos usualmente con operadores de comparación, tal como se describe en la sección [comparaciones]. También puedes crearlos manualmente con la función `c()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1:10 %% 3 == 0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE\n```\n:::\n\n```{.r .cell-code}\nc(TRUE, TRUE, FALSE, NA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  TRUE  TRUE FALSE    NA\n```\n:::\n:::\n\n\n### Numérico\n\nLos vectores de tipo entero y doble se conocen de manera colectiva como vectores numéricos. En R, los números por defecto son representados como _double_. Para generar un entero, coloca una L después del número:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(1L)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"integer\"\n```\n:::\n\n```{.r .cell-code}\n1.5L\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.5\n```\n:::\n:::\n\n\nLa distinción entre enteros y dobles usualmente no resulta importante, aunque existen dos diferencias relevantes de las que debes ser consciente:\n\n1. Los números dobles son aproximaciones. Representan números de punto flotante que no siempre pueden ser representados de manera precisa con un cantidad fija de memoria. Esto significa que debes considerar a todos los dobles como aproximaciones. Por ejemplo, ¿cuál es el cuadrado de la raíz cuadrada de dos?\n\n\n\n ::: {.cell}\n \n ```{.r .cell-code}\n x <- sqrt(2) ^ 2\n x\n ```\n \n ::: {.cell-output .cell-output-stdout}\n ```\n [1] 2\n ```\n :::\n \n ```{.r .cell-code}\n x - 2\n ```\n \n ::: {.cell-output .cell-output-stdout}\n ```\n [1] 4.440892e-16\n ```\n :::\n :::\n\n\nEste comportamiento es común cuando trabajas con números de punto flotante: la mayoría de los cálculos incluyen algunos errores de aproximación. En lugar de comparar números de punto flotante usando `==`, debes usar ´dplyr::near()`, que provee tolerancia numérica.\n\n2. Los números enteros tienen un valor especial, `NA`, mientras que los dobles tienen cuatro tipos: `NA`, `NaN`, `Inf` y `–Inf`. Los tres valores especiales `NaN`, `Inf` y `-Inf` pueden surgir durante una división:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(-1, 0, 1) / 0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -Inf  NaN  Inf\n```\n:::\n:::\n\n\nEvita usar `==` para chequear estos valores especiales. En su lugar usa la funciones de ayuda `is.finite()`, `is.infinite()`, y `is.nan()`:\n\n\n\n | | 0 | Inf | NA | NaN |\n |------------------|-----|-----|-----|-----|\n | `is.finite()` | x | | | |\n | `is.infinite()` | | x | | |\n | `is.na()` | | | x | x |\n | `is.nan()` | | | | x |\n\n### Caracter\n\nLos vectores de caracteres son los tipos de vectores atómicos más complejos, ya que cada elemento del mismo es un _string_ (una cadena de caracteres) y un _string_ puede contener una cantidad arbitraria de datos.\nYa has aprendido un montón acerca de cómo trabajar con _strings_ en el capítulo sobre [Cadenas de caracteres]. Pero queremos mencionar una característica importante de la implementación que subyace a los _strings_: R usa una reserva global de _strings_. Esto significa que cada string único solo es almacenado en la memoria una vez y cada uso de un _string_ apunta a esa representación. Esto reduce la cantidad de memoria necesaria para _strings_ duplicados. Puedes ver este comportamiento en práctica con `pryr::object_size()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- \"Esta es una cadena de caracteres razonablemente larga.\"\npryr::object_size(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n168 B\n```\n:::\n\n```{.r .cell-code}\ny <- rep(x, 1000)\npryr::object_size(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n8.16 kB\n```\n:::\n:::\n\n`y` no utiliza 1000 veces más memoria que `x`, ya que cada elemento de `y` solo apunta al mismo _string_. Cada uno de estos _punteros_ utiliza 8 bytes, por lo que 1000 punteros hacia un _string_ de 168 B es igual a 8 * 1000 + 168 = 8.16 kB.\n\n### Valores faltantes\n\nCada tipo de vector atómico tiene su propio valor faltante (_missing value_):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA # lógico\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\nNA_integer_ # entero\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\nNA_real_ # doble o real\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\nNA_character_ # caracter\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n\nNormalmente no necesitas saber sobre los diferentes tipos porque siempre puedes usar `NA` (del inglés _Not Available_, _no disponible_), el que se convertirá al tipo correcto usando las reglas implícitas de coerción. Sin embargo, existen algunas funciones que son estrictas acerca de sus inputs, por lo que es útil tener presente este conocimiento, así tu código puede ser lo suficientemente específico cuando lo necesites.\n\n### Ejercicios\n\n1. Describe la diferencia entre `is.finite(x)` y `!is.infinite(x)`.\n1. Lee el código fuente de `dplyr:: near()` (Pista: para ver el código fuente, escribe el nombre de la función sin `()`). ¿Funcionó?\n1. Un vector de tipo lógico puede tomar 3 valores posibles. ¿Cuántos valores posibles puede tomar un vector de tipo entero? ¿Cuántos valores posibles puede tomar un vector de tipo doble? Usa google para investigar sobre esto.\n1. Idea al menos 4 funciones que te permitan convertir un vector de tipo doble a entero. ¿En qué difieren las funciones? Describe las diferencias con precisión.\n1. ¿Qué funciones del paquete **readr** te permiten convertir una cadena de caracteres en un vector de tipo lógico, entero y doble?\n\n## Usando vectores atómicos\n\nAhora que conoces los diferentes tipos de vectores atómicos, es útil repasar algunas herramientas importantes para trabajar con ellos. Estas incluyen:\n\n1.\tCómo realizar una conversión de un determinado tipo a otro y en qué casos esto sucede automáticamente.\n2.\tCómo decidir si un objeto es de un tipo específico de vector.\n3.\tQué sucede cuando trabajas con vectores de diferentes longitudes.\n4.\tCómo nombrar los elementos de un vector\n5.\tCómo extraer los elementos de interés de un vector.\n\n### Coerción\n\nExisten dos maneras de convertir, o coercionar, un tipo de vector a otro:\n\n1. La coerción explícita ocurre cuando llamas una función como `as.logical()`, `as.integer()`, `as.double()`, o `as.character()`. Cuando te encuentres usando coerción expíicita, comprueba si es posible hacer algún tipo de arreglo antes que permita que al vector nunca se le llegue a asignar el tipo incorrecto. Por ejemplo, podrías necesitar ajustar la especificación de `col_types` (_tipos de columna_) del paquete **readr** cuando importas los datos.\n\n1. La coerción implícita ocurre cuando usas un vector en un contexto específico en el que se espera que sea de cierto tipo. Por ejemplo, cuando usas un vector de tipo lógico con la función numérica `summary` (_resumen_), o cuando usas un vector de tipo doble donde se espera que sea de tipo entero.\nDebido a que la coerción explícita se usa raramente y es mucho más fácil de entender, nos enfocaremos acá en la coerción implícita.\nYa viste el tipo más importante de coerción implícita: cuando se usa un vector de tipo lógico en un contexto numérico. En ese caso, el valor `TRUE` es convertido a `1` y `FALSE` a `0`. Esto significa que la suma de un vector de tipo lógico es el número de valores verdaderos, y que la media es de un vector lógico es la proporción de valores verdaderos:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- sample(20, 100, replace = TRUE)\ny <- x > 10\nsum(y) # ¿Cuántos valores son más grandes que 10?\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 49\n```\n:::\n\n```{.r .cell-code}\nmean(y) # ¿Qué proporción es mayor que 10?\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.49\n```\n:::\n:::\n\n\nQuizás veas código (usualmente más antiguo) que se basa en la coerción implícita en la dirección opuesta, es decir, de un valor entero a uno lógico:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (length(x)) {\n # hacer algo\n}\n```\n:::\n\n\nEn este caso, `0` es convertido a `FALSE` y todo lo demás es convertido a `TRUE`. Creemos que esto hace que tu código sea más difícil de entender, por lo que no lo recomendamos. En su lugar, utiliza explícitamente: `length(x) > 0`.\n\nEs también importante entender qué ocurre cuando creas un vector que contiene múltiples tipos usando `c()`: los tipos más complejos siempre ganan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(c(TRUE, 1L))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"integer\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(c(1L, 1.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(c(1.5, \"a\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n:::\n\n\nUn vector atómico no puede contener una mezcla de diferentes tipos, ya que el tipo es una propiedad del vector completo, no de los elementos individuales. Si necesitas mezclar diferentes tipos en el mismo vector, entonces deberías utilizar una lista, sobre la que aprenderás en breve.\n\n### Funciones de prueba\n\nAlgunas veces quieres diferentes cosas dependiendo del tipo de vector. Una opción es utilizar `typeof()`; otra es usar una función de prueba que devuelva `TRUE` o `FALSE`. Si bien R base provee muchas funciones como `is.vector()` e `is.atomic()`, estas a menudo devuelven resultados inesperados. En su lugar, es más seguro utilizar las funciones `is_*` provistas por el paquete **purrr**, que se resumen en la tabla de más abajo. \n\n| | lgl | int | dbl | chr | list |\n|------------------|-----|-----|-----|-----|------|\n| `is_logical()` | x | | | | |\n| `is_integer()` | | x | | | |\n| `is_double()` | | | x | | |\n| `is_numeric()` | | x | x | | |\n| `is_character()` | | | | x | |\n| `is_atomic()` | x | x | x | x | |\n| `is_list()` | | | | | x |\n| `is_vector()` | x | x | x | x | x |\n\n\n### Escalares y reglas de reciclado\n\nAsí como se coercionan implícitamente los tipos de vectores para que sean compatibles, R también implicitamente coerciona la longitud de los vectores. Esto se denomina __reciclado__ de vectores (_vector recicling_), debido a que el vector de menor longitud se repite, o recicla, hasta igualar la longitud del vector más largo.\nGeneralmente, esto es más útil cuando estás trabajando con vectores y \"escalares\". Hemos puesto \"escalares\" entre comillas porque R en realidad no tiene escalares: en su lugar, un solo número es un vector de longitud 1. Debido a que no existen los escalares, la mayoría de las funciones pre-definidas están vectorizadas, lo que implica que operarán en un vector de números. Esa es la razón de por qué, por ejemplo, el siguiente código funciona:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample(10) + 100 # (sample = muestreo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 110 101 106 109 103 108 105 104 107 102\n```\n:::\n\n```{.r .cell-code}\nrunif(10) > 0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE\n```\n:::\n:::\n\nEn R, las operaciones matemáticas básicas funcionan con vectores. Esto significa que nunca necesitarás la ejecución de una interacción explícita cuando realices cálculos matemáticos sencillos.\nEs intuitivo lo que debería pasar si agregas dos vectores de la misma longitud, o un vector y un \"escalar\". Pero ¿qué sucede si agregas dos vectores de diferentes longitudes?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1:10 + 1:2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  2  4  4  6  6  8  8 10 10 12\n```\n:::\n:::\n\nAquí, R expandirá el vector más corto a la misma longitud del vector más largo, que es lo que denominamos _reciclaje_. Esto se realiza de manera silenciosa, excepto cuando la longitud del vector más largo no es un múltiplo entero de la longitud del vector más corto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1:10 + 1:3\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in 1:10 + 1:3: longer object length is not a multiple of shorter object\nlength\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  2  4  6  5  7  9  8 10 12 11\n```\n:::\n:::\n\nSi bien el vector reciclado puede ser usado para crear código sucinto e ingenioso, también puede ocultar problemas de manera silenciosa. Por esta razón, las funciones vectorizadas en el tidyverse mostrarán errores cuando reciclas cualquier otra cosa que no sea un escalar. Si realmente quieres reutilizar, necesitarás hacerlo de manera explícita con `rep()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = 1:4, y = 1:2)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `tibble()`:\n! Tibble columns must have compatible sizes.\n• Size 4: Existing data.\n• Size 2: Column `y`.\nℹ Only values of size one are recycled.\n```\n:::\n\n```{.r .cell-code}\ntibble(x = 1:4, y = rep(1:2, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n      x     y\n  <int> <int>\n1     1     1\n2     2     2\n3     3     1\n4     4     2\n```\n:::\n\n```{.r .cell-code}\ntibble(x = 1:4, y = rep(1:2, each = 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n      x     y\n  <int> <int>\n1     1     1\n2     2     1\n3     3     2\n4     4     2\n```\n:::\n:::\n\n### Nombrar vectores\n\nTodos los tipos de vectores pueden ser nombrados. Puedes asignarles un nombre al momento de crearlos con `c()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(x = 1, y = 2, z = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nx y z \n1 2 4 \n```\n:::\n:::\n\n\nO después de haberlos creado con `purrr::set_names()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset_names(1:3, c(\"a\", \"b\", \"c\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\na b c \n1 2 3 \n```\n:::\n:::\n\nLos vectores con nombres son particularmente útiles para la creación de subconjuntos, como se describe a continuación.\n\n### Creación de subconjuntos (_subsetting_){#vector-subsetting}\n\nHasta ahora hemos utilizado `dplyr::filter()` para filtrar filas en un tibble. `filter()` solo funciona con tibbles, por lo que necesitaremos una nueva herramienta para trabajar con vectores: `[`. `[`  es la función para crear subconjuntos (_subsetting_) y podemos llamarla como `x[a]`. Existen cuatro tipos de cosas con las que puedes un crear un _subset_ de un vector:\n\n1. Un vector numérico que contenga solo enteros. Los enteros deben ser todos positivos, todos negativos, o cero.\n\n        Crear subconjuntos con enteros positivos mantiene los elementos en aquellas posiciones:\n        \n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(\"uno\", \"dos\", \"tres\", \"cuatro\", \"cinco\")\nx[c(3, 2, 5)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"tres\"  \"dos\"   \"cinco\"\n```\n:::\n:::\n\n        \n        Repitiendo una posición, puedes en realidad generar un output de mayor longitud que el input:\n        \n\n::: {.cell}\n\n```{.r .cell-code}\nx[c(1, 1, 5, 5, 5, 2)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"uno\"   \"uno\"   \"cinco\" \"cinco\" \"cinco\" \"dos\"  \n```\n:::\n:::\n\n\n        Los valores negativos eliminan elementos en las posiciones especificadas:\n        \n\n::: {.cell}\n\n```{.r .cell-code}\nx[c(-1, -3, -5)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"dos\"    \"cuatro\"\n```\n:::\n:::\n\n\n        Es un error mezclar valores positivos y negativos:\n        \n        \n\n::: {.cell}\n\n```{.r .cell-code}\nx[c(1, -1)]\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in x[c(1, -1)]: only 0's may be mixed with negative subscripts\n```\n:::\n:::\n\n        \n        El mensaje menciona crear subsets utilizando cero, lo que no retorna valores.\n        \n\n::: {.cell}\n\n```{.r .cell-code}\nx[0]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncharacter(0)\n```\n:::\n:::\n\n        \n        Esto a menudo no es útil, pero puede ser de ayuda si quieres crear estructuras de datos inusuales con las que testear tus funciones.\n        \n\n2. Crear subsets con un vector lógico mantiene todos los valores que  correspondan al valor `TRUE`. Esto es usualmente útil en conjunto con las funciones de comparación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(10, 3, NA, 5, 8, 1, NA)\n        \n# Todos los valores no faltantes de x\nx[!is.na(x)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10  3  5  8  1\n```\n:::\n\n```{.r .cell-code}\n# Todos los valores pares (o faltantes!) de x\nx[x %% 2 == 0]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 NA  8 NA\n```\n:::\n:::\n\n\n3. Si tienes un vector con nombre, puedes subdivirlo en un vector de tipo caracter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(abc = 1, def = 2, xyz = 5)\nx[c(\"xyz\", \"def\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nxyz def \n  5   2 \n```\n:::\n:::\n\n\n        Al igual que con los enteros positivos, también puedes usar un vector del tipo caracter para duplicar entradas individuales.\n\n4. El tipo más sencillo de _subsetting_ es nada, `x[]`, lo que retorna el valor completo de `x`. Esto no es útil para crear subconjuntos de vectores, pero sí lo es para el caso de las matrices (y otras estructuras de alta dimensionalidad), ya que te permite seleccionar toda las filas o todas las columnas, dejando el índice en blanco. Por ejemplo, si `x` tiene dos dimensiones, `x[1, ]` selecciona la primera fila y todas las columnas y `x[, -1]` selecciona todas las filas y todas las columnas excepto la primera.\n\nPara aprender más acerca de las aplicaciones de la creación de subconjuntos, puedes leer el capítulo \"Subsetting\" de _Advanced R_: <http://adv-r.hadley.nz/Subsetting.html#applications>.\n\nExiste una importante variación de `[` llamada `[[`. `[[` solo extrae un único elemento y siempre descarta nombres. Es una buena idea usarla cada vez que quieras dejar en claro que estás extrayendo un único item, como en un bucle _for_ (_for loop_). La diferencia entre `[` y`[[` es más importante para el caso de las listas, como veremos en breve.\n\n### Ejercicios\n\n1. ¿Qué es lo que `mean(is.na(x))` te dice acerca del vector 'x'? ¿Y qué es lo que te dice `sum(!is.finite(x))`?\n\n1. Lee detenidamente la documentación de `is.vector()`. ¿Qué es lo que esta función realmente testea? ¿Por qué la función `is.atomic()` no concuerda con la definición de vectores atómicos vista anteriormente?\n\n1. Compara y contrasta `setNames()` con `purrr::set_names()`.\n\n1. Crea funciones que tomen un vector como input y devuelvan:\n\t1. El último valor. ¿Deberías usar `[` o `[[`?\n\t1. Los elementos en posiciones pares.\n\t1. Cada elemento excepto el último valor.\n\t1. Solo las posiciones pares (sin valores perdidos).\n\n1. ¿Por qué `x[-which(x > 0)]` no es lo mismo que `x[x <= 0]`?\n\n1. ¿Qué sucede cuando realizas un subset con un entero positivo que es mayor que la longitud del vector? ¿Qué sucede cuando realizas un subset con un nombre que no existe?\n\n## Vectores Recursivos (listas)\n\nLas listas son un escalón más en complejidad respecto de los vectores atómicos, ya que pueden contener otras listas en su interior. Esto las hace adecuadas para representar estructuras jerárquicas o de tipo árbol. Puedes crear una lista con ´list()´:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- list(1, 2, 3) \nx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n[1] 1\n\n[[2]]\n[1] 2\n\n[[3]]\n[1] 3\n```\n:::\n:::\n\nUn herramienta muy útil para trabajar con listas es `str()` ya que se enfoca en la e**str**uctura, no en los contenidos.\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 3\n $ : num 1\n $ : num 2\n $ : num 3\n```\n:::\n\n```{.r .cell-code}\nx_nombrada <- list(a = 1, b = 2, c = 3)\nstr(x_nombrada)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 3\n $ a: num 1\n $ b: num 2\n $ c: num 3\n```\n:::\n:::\n\n\nA diferencia de los vectores atómicos, ´list()´ puede contener una mezcla de objetos:\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- list(\"a\", 1L, 1.5, TRUE)\nstr(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 4\n $ : chr \"a\"\n $ : int 1\n $ : num 1.5\n $ : logi TRUE\n```\n:::\n:::\n\n\n¡Las listas incluso pueden contener otras listas!\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- list(list(1, 2), list(3, 4))\nstr(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 2\n $ :List of 2\n  ..$ : num 1\n  ..$ : num 2\n $ :List of 2\n  ..$ : num 3\n  ..$ : num 4\n```\n:::\n:::\n\n\n### Visualizando listas\n\nPara explicar funciones de manipulación de listas más complejas, es útil tener una representacion visual de las listas. Por ejemplo, considera estas tres listas:\n\n::: {.cell}\n\n```{.r .cell-code}\nx1 <- list(c(1, 2), c(3, 4))\nx2 <- list(list(1, 2), list(3, 4))\nx3 <- list(1, list(2, list(3)))\n```\n:::\n\n\nAsí es como las representaremos visualmente:\n\n::: {.cell}\n::: {.cell-output-display}\n![](diagrams_w_text_as_path/es/lists-structure.svg){width=75%}\n:::\n:::\n\n\nExisten tres principios en la imagen anterior:\n\n1.\tLas listas tienen esquinas redondeadas; los vectores atómicos esquinas cuadradas.\n2.\tLos elementos hijos están dibujados dentro de sus padres y tienen un fondo ligeramente más oscuro para facilitar la visualización de la jerarquía.\n3.\tNo es importante la orientación de los elementos hijos (esto es, las filas o columnas), por lo que si elegimos determinada orientación será para ahorrar espacio o para ilustrar una propiedad importante en el ejemplo.\n\n### Subconjuntos (_Subsetting_)\nExisten tres maneras de extraer subconjuntos de una lista, los que ilustraremos con una lista denominada `a`:\n\n::: {.cell}\n\n```{.r .cell-code}\na <- list(a = 1:3, b = \"una cadena\", c = pi, d = list(-1, -5))\n```\n:::\n\n\n* El corchete simple `[` extrae una sub-lista. El resultado siempre será una lista.\n        \n\n::: {.cell}\n\n```{.r .cell-code}\nstr(a[1:2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 2\n $ a: int [1:3] 1 2 3\n $ b: chr \"una cadena\"\n```\n:::\n\n```{.r .cell-code}\nstr(a[4])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 1\n $ d:List of 2\n  ..$ : num -1\n  ..$ : num -5\n```\n:::\n:::\n\n        \n        Al igual que con los vectores, puedes extraer subconjuntos con un vector lógico, de enteros o de caracteres.\n\n* El doble corchete `[[` extrae un solo componente de una lista. Elimina un nivel de la jerarquía de la lista.\n        \n\n::: {.cell}\n\n```{.r .cell-code}\nstr(a[[1]])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n int [1:3] 1 2 3\n```\n:::\n\n```{.r .cell-code}\nstr(a[[4]])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 2\n $ : num -1\n $ : num -5\n```\n:::\n:::\n\n\n* `$` es un atajo para extraer elementos con nombre de una lista. Funciona de modo similar al doble corchete `[[`, excepto que no necesitas utilizar comillas.\n        \n\n::: {.cell}\n\n```{.r .cell-code}\na$a\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1 2 3\n```\n:::\n\n```{.r .cell-code}\na[[\"a\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1 2 3\n```\n:::\n:::\n\n\nLa diferencia entre `[` y `[[` es muy importante para las listas, ya que `[[` se adentra en una lista mientras que `[` retorna una lista nueva, más pequeña. Compara el código y el output de arriba con la representación visual de la Figura \\@ref(fig:lists-subsetting).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Subdividir una lista, de manera visual.](diagrams_w_text_as_path/es/lists-subsetting.svg){width=75%}\n:::\n:::\n\n\n### Listas de Condimentos\nLa diferencia entre `[` y `[[` es muy importante, pero es muy fácil confundirse. Para ayudarte a recordar, te mostraremos un pimentero inusual.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/pepper.jpg){width=25%}\n:::\n:::\n\n\nSi este pimientero es tu lista `x`, entonces, `x[1]` es un pimientero que contiene un solo paquete de pimienta:\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/pepper-1.jpg){width=25%}\n:::\n:::\n\n\n`x[2]` luciría igual, pero contendría el segundo paquete. `x[1:2]` sería un pimentero que contiene dos paquetes de pimienta.\n\n`x[[1]]` es:\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/pepper-2.jpg){width=25%}\n:::\n:::\n\nSi quisieras obtener el contenido del paquete de pimienta, necesitarías utilizar `x[[1]][[1]`:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/pepper-3.jpg){width=25%}\n:::\n:::\n\n\n### Ejercicios\n1.Dibuja las siguientes listas como sets anidados:\n\n        1. `list(a, b, list(c, d), list(e, f))`\n        1. `list(list(list(list(list(list(a))))))`\n\n2.¿Qué pasaría si hicieras _subsetting_ a un tibble como si fuera una lista? ¿Cuáles son las principales diferencias entre una lista y un tibble?\n\n## Atributos\n\nCualquier vector puede contener metadatos arbitrarios adicionales mediante sus **atributos**. Puedes pensar en los atributos como una lista de vectores con nombre que pueden ser adjuntadas a cualquier otro objeto. Puedes obtener y definir valores de atributos individuales con `attr()` o verlos todos al mismo tiempo con `attributes()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1:10\nattr(x, \"saludo\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNULL\n```\n:::\n\n```{.r .cell-code}\nattr(x, \"saludo\") <- \"¡Hola!\"\nattr(x, \" despedida\") <- \"¡Adiós!\"\nattributes(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$saludo\n[1] \"¡Hola!\"\n\n$` despedida`\n[1] \"¡Adiós!\"\n```\n:::\n:::\n\n\nExisten tres atributos muy importantes que son utilizados para implementar partes fundamentals de R:\n\n1.\tLos __nombres__ son utilizados para nombrar los elementos de un vector.\n\n2.\tLas __dimensiones__ (o dims, abreviado) hacen que un vector se comporte como una matriz o _array_.\n\n3.\tLa __clase__ es utilizada para implementar el sistema orientado a objetos S3.\n\nYa revisamos los nombres más arriba y no abordaremos las dimensiones porque en este libro no utilizamos matrices. Nos queda describir el atributo _clase_, que controla cómo trabajan las **funciones genéricas**. Las funciones genéricas son clave para la programación orientada a objetos en R, ya que hacen que las funciones se comporten de manera diferente para diferentes clases de inputs. Está fuera del alcance de este libro tener una discusión más profunda sobre la programacion orientada a objetos, pero puedes leer más al respecto en el libro _Advanced R_: <https://adv-r.hadley.nz/s3.html>.\n\nAsí es como luce una función genérica típica:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.Date\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction (x, ...) \nUseMethod(\"as.Date\")\n<bytecode: 0x55a8d3dbcdd0>\n<environment: namespace:base>\n```\n:::\n:::\n\n\nLa llamada a \"UseMethod\" significa que esta es una función genérica y que llamará a un **método** específico, esto es, una función basada en la clase del primer argumento. (Todos los métodos son funciones; no todas las funciones son métodos). Puedes listar todos los métodos existentes para una función genérica con `methods()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmethods(\"as.Date\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] as.Date.character*  as.Date.default*    as.Date.factor*    \n[4] as.Date.numeric*    as.Date.POSIXct*    as.Date.POSIXlt*   \n[7] as.Date.vctrs_sclr* as.Date.vctrs_vctr*\nsee '?methods' for accessing help and source code\n```\n:::\n:::\n\n\nPor ejemplo, si `x` es un vector de caracteres, `as.Date()` llamará a `as.Date.character()`; si es un factor, llamará a `as.Date.factor()`.\n\nPuedes ver la implementación específica de un método con: `getS3method()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetS3method(\"as.Date\", \"default\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction (x, ...) \n{\n    if (inherits(x, \"Date\")) \n        x\n    else if (is.null(x)) \n        .Date(numeric())\n    else if (is.logical(x) && all(is.na(x))) \n        .Date(as.numeric(x))\n    else stop(gettextf(\"do not know how to convert '%s' to class %s\", \n        deparse1(substitute(x)), dQuote(\"Date\")), domain = NA)\n}\n<bytecode: 0x55a8d963d118>\n<environment: namespace:base>\n```\n:::\n\n```{.r .cell-code}\ngetS3method(\"as.Date\", \"numeric\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction (x, origin, ...) \nif (missing(origin)) .Date(x) else as.Date(origin, ...) + x\n<bytecode: 0x55a8d969d198>\n<environment: namespace:base>\n```\n:::\n:::\n\nLa S3 genérica más importante es `print()`: controla cómo el objeto es impreso cuando tipeas su nombre en la consola. Otras funciones genéricas importantes son las funciones de subconjuntos `[`, `[[` y `$`.\n\n## Vectores aumentados\n\nLos vectores atómicos y las listas son los bloques sobre los que se construyen otros tipos importantes de vectores, como factores y fechas. A estos vectores le llamamos __vectores aumentados__, ya que son vectores con __atributos__ adicionales, incluyendo la clase. Debido a que los vectores aumentados tienen una clase, se comportan de manera diferente a los vectores atómicos sobre los que están construidos. En este libro, hacemos uso de cuatro importantes vectores aumentados:\n\n* Factores\n* Fechas\n* Fechas-hora\n* Tibbles\n\nA continuación encontrarás una descripción de cada uno de ellos.\n\n### Factores\n\nLos factores están diseñados para representar datos categóricos que pueden tomar un set fijo de valores posibles. Están construidos sobre la base de enteros y tienen un atributo de _niveles_ (_levels_):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- factor(c(\"ab\", \"cd\", \"ab\"), levels = c(\"ab\", \"cd\", \"ef\"))\ntypeof(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"integer\"\n```\n:::\n\n```{.r .cell-code}\nattributes(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$levels\n[1] \"ab\" \"cd\" \"ef\"\n\n$class\n[1] \"factor\"\n```\n:::\n:::\n\n\n### Fechas y fechas-hora\n\nLas fechas en R son vectores numéricos que representan el número de días desde el 1° de enero de 1970.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- as.Date(\"1971-01-01\")\nunclass(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365\n```\n:::\n\n```{.r .cell-code}\ntypeof(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\nattributes(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$class\n[1] \"Date\"\n```\n:::\n:::\n\nLos vectores fecha-hora son vectores numéricos de clase `POSIXct`, que representan el número de segundos desde el 1° de enero de 1970. (En caso de que te lo preguntes, \"POSIXct\" es el acrónimo de _\"Portable Operating System Interface\" calendar time_, es decir, tiempo calendario de la interfaz portable del sistema operativo\")\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- lubridate::ymd_hm(\"1970-01-01 01:00\")\nunclass(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3600\nattr(,\"tzone\")\n[1] \"UTC\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\nattributes(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$class\n[1] \"POSIXct\" \"POSIXt\" \n\n$tzone\n[1] \"UTC\"\n```\n:::\n:::\n\nEl atributo `tzone` es opcional. Controla cómo se imprime la hora, no a qué tiempo absoluto hace referencia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattr(x, \"tzone\") <- \"US/Pacific\"\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1969-12-31 17:00:00 PST\"\n```\n:::\n\n```{.r .cell-code}\nattr(x, \"tzone\") <- \"US/Eastern\"\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1969-12-31 20:00:00 EST\"\n```\n:::\n:::\n\nExiste otro tipo de fechas-hora llamado POSIXlt. Estos se construyen sobre la base de listas nombradas (_named lists_).\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- as.POSIXlt(x)\ntypeof(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"list\"\n```\n:::\n\n```{.r .cell-code}\nattributes(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$names\n [1] \"sec\"    \"min\"    \"hour\"   \"mday\"   \"mon\"    \"year\"   \"wday\"   \"yday\"  \n [9] \"isdst\"  \"zone\"   \"gmtoff\"\n\n$class\n[1] \"POSIXlt\" \"POSIXt\" \n\n$tzone\n[1] \"US/Eastern\" \"EST\"        \"EDT\"       \n\n$balanced\n[1] TRUE\n```\n:::\n:::\n\n\nLos POSIXlts son pocos comunes dentro del tidyverse. Sí lo son en R base, ya que son necesarios para extraer components específicos de una fecha, como el año o el mes. Debido a que el paquete **lubridate** provee funciones de ayuda para efectuar dicha extracción, ya no los necesitarás. Siempre es más sencillo trabajar con POSIXct, por lo que si te encuentras con un POSIXlt, deberías convertirlo a un vector de fecha-hora con `lubridate::as_date_time()`.\n\n### Tibbles\nLos tibbles son listas aumentadas: tienen las clases \"tbl_df\", \"tbl\" y \"data.frame\", y atributos `names` (para columna) y `row.names` (para fila):\n\n::: {.cell}\n\n```{.r .cell-code}\ntb <- tibble::tibble(x = 1:5, y = 5:1)\ntypeof(tb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"list\"\n```\n:::\n\n```{.r .cell-code}\nattributes(tb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$class\n[1] \"tbl_df\"     \"tbl\"        \"data.frame\"\n\n$row.names\n[1] 1 2 3 4 5\n\n$names\n[1] \"x\" \"y\"\n```\n:::\n:::\n\nLa diferencia entre un tibble y una lista, consiste en que todos los elementos de un data frame deben ser vectores de la misma longitud. Todas las funciones que utilizan tibbles imponen esta condición.\n\nLos data.frames tradicionales tienen una estructura muy similar a los tibbles:\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(x = 1:5, y = 5:1)\ntypeof(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"list\"\n```\n:::\n\n```{.r .cell-code}\nattributes(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$names\n[1] \"x\" \"y\"\n\n$class\n[1] \"data.frame\"\n\n$row.names\n[1] 1 2 3 4 5\n```\n:::\n:::\n\nLa diferencia principal entre ambos es la clase. La clase tibble incluye \"data.frame\", lo que significa que los tibbles heredan el comportamiento regular de un data frame por defecto.\n\n### Ejercicios:\n\n1.\t¿Qué valor retorna `hms::hms(3600)`? ¿Cómo se imprime? ¿Cuál es la tipo primario sobre en el que se basa el vector aumentado? ¿Qué atributos utiliza?\n\n2.\tIntenta crear un tibble que tenga columnas con diferentes longitudes. ¿Qué es lo que ocurre?\n\n3.\tTeniendo en cuenta la definición anterior, ¿está bien tener una lista como columna en un tibble?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}