{
  "hash": "ebfc9e1c6ef7d78e6ecdb39b4980a60b",
  "result": {
    "markdown": "# Pipes\n\n## Introducción\n\nLos pipes son una herramienta poderosa para expresar claramente una secuencia de múltiples operaciones. Hasta aquí, has venido usándolos sin saber cómo funcionan o qué alternativas existen. En este capítulo ya es tiempo de explorarlos en más detalle. En él aprenderás qué alternativas existen, cuándo no deberías utilizarlos y algunas herramientas útiles relacionadas.\n\n### Prerequisitos\n\nEl pipe, `%>%`, viene del paquete __magrittr__ de Stefan Milton Bache. Los paquetes del Tidyverse cargan `%>%` automáticamente, por lo que usualmente no tendrás que cargar __magrittr__ de forma explícita. Sin embargo, como acá nos enfocaremos en el uso de pipes y no usaremos otros paquetes del tidyverse, lo cargaremos explícitamente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(magrittr)\nlibrary(datos)\n```\n:::\n\n\n## Alternativas a los pipes\n\nEl objetivo de un pipe es ayudarte a escribir código de una manera que sea más fácil de leer y entender. Para ver por qué un pipe es tan útil, vamos a explorar diferentes formas de escribir el mismo código. Usemos código para contar una historia acerca de un pequeño conejito llamado Foo Foo:\n\n> El pequeño conejito Foo Foo\n> Fue saltando por el bosque\n> Recogiendo ratones del campo\n> Y golpeándolos en la cabeza\n\nEste es un poema popular para niños que se acompaña mediante gestos con las manos.\n\nEmpezaremos por definir un objeto que represente al pequeño conejito Foo Foo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoo_foo <- pequeño_conejito()\n```\n:::\n\n\nY usaremos una función para cada verbo clave: `saltar()`, `recoger()`, y `golpear()`. Usando este objeto y estos verbos, existen (al menos) cuatro maneras en las que podemos volver a contar la historia en código:\n\n1.\tGuardar cada paso intermedio como un nuevo objeto.\n2.\tSobreescribir el objeto original muchas veces.\n3.\tComponer funciones.\n4.\tUsar un pipe.\n\nDesarrollaremos cada uno de estos enfoques, mostrándote el código y hablando de las ventajas y desventajas.\n\n\n### Pasos intermedios\n\nEl enfoque más sencillo es guardar cada paso como un nuevo objeto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoo_foo_1 <- saltar(foo_foo, a_traves = bosque)\nfoo_foo_2 <- recoger(foo_foo_1, que = ratones_del_campo)\nfoo_foo_3 <- golpear(foo_foo_2, en = cabeza)\n```\n:::\n\n\nLa principal desventaja de esta manera es que te obliga a nombrar cada paso intermedio. Si hay nombres naturales, es una buena idea y deberías hacerlo. Pero muchas veces, como en este ejemplo, no hay nombres naturales, por lo que agregas sufijos numéricos para hacer los nombres únicos. Esto conduce a dos problemas:\n\n1. El código está abarrotado con nombres poco importantes.\n\n2. Hay que incrementar cuidadosamente el sufijo en cada línea.\n\nCada vez que escribimos código como este, nos ocurre que inevitablemente usamos el número incorrecto en una línea y luego perdemos 10 minutos rascándonos la cabeza tratándo de darnos cuenta por qué no funciona. \nProbablemente te preocupa también que esta forma crea muchas copias de tus datos y ocupa demasiada memoria. Sorprendentemente, este no es el caso. Primero, ten en cuenta que preocuparse proactivamente de la memoria no es una manera útil de invertir tu tiempo: preocúpate acerca de ello cuando se convierta en un problema (es decir, cuando te quedes sin memoria), no antes. En segundo lugar, R no es estúpido y compartirá las columnas a lo largo de los dataframes cuando sea posible. Echemos un vistazo a un pipe de manipulación de datos en el que agregamos una nueva columna a `datos::diamantes`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiamantes2 <- diamantes %>%\n  dplyr::mutate(precio_por_quilate = precio / quilate)\n\npryr::object_size(diamantes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.46 MB\n```\n:::\n\n```{.r .cell-code}\npryr::object_size(diamantes2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.89 MB\n```\n:::\n\n```{.r .cell-code}\npryr::object_size(diamantes, diamantes2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.89 MB\n```\n:::\n:::\n\n\n`pryr::object_size()` (_tamaño de objeto_) devuelve la cantidad de memoria ocupada por todos los argumentos de un objeto. Los resultados parecen contraintuitivos al principio:\n\n* `diamantes` ocupa 3.46 MB,\n* `diamantes2` ocupa 3.89 MB,\n* ¡`diamantes` y `diamantes2` juntos ocupan 3.89 MB!\n\n¿Cómo es que funciona esto? Bien, `diamantes2` tiene 10 columnas en común con `diamantes`: no hay necesidad de duplicar los datos, así que ambos data frames tienen variables en común. Estas variables solo serán copiadas si modificas una de ellas. En el siguiente ejemplo, modificamos un solo valor en `diamantes$quilate`. Esto significa que la variable `quilate` no podrá ser compartida entre los dos data frames, por lo que se debe realizar una copia. El tamaño de cada data frame no cambia, pero el tamaño colectivo se incrementa:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiamantes$quilate[1] <- NA\npryr::object_size(diamantes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.46 MB\n```\n:::\n\n```{.r .cell-code}\npryr::object_size(diamantes2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.89 MB\n```\n:::\n\n```{.r .cell-code}\npryr::object_size(diamantes, diamantes2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n4.32 MB\n```\n:::\n:::\n\n\n(Fíjate que aquí usamos `pryr::object_size()`, no la versión de `object.size()` ya precargada. `object.size()` toma un solo objeto, por lo que no puede computar cómo los datos son compartidos a través de múltiples objetos.)\n\n### Sobrescribir el original\n\nEn vez de crear objetos en cada paso intermedio, podemos sobrescribir el objeto original:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoo_foo <- saltar(foo_foo, a_traves = bosque)\nfoo_foo <- recoger(foo_foo, que = ratones_del_campo)\nfoo_foo <- golpear(foo_foo, en = cabeza)\n```\n:::\n\n\nEsto es menos tipeo (y menos que pensar), así que es menos probable que cometas errores. Sin embargo, hay dos problemas:\n\n1. Depurar es doloroso: si cometes un error vas a necesitar correr de nuevo todo el código desde el principio.\n\n2. La repetición del objeto a medida que es transformado (¡hemos escrito foo_foo 6 veces!) hace poco transparente lo que está siendo cambiado en cada línea.\n\n### Composición de funciones\n\nOtro enfoque es abandonar la asignación y encadenar todas las llamadas a las funciones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngolpear(\n  recoger(\n    saltar(foo_foo, a_traves = bosque),\n    que = raton_de_campo\n  ),\n  en = la_cabeza\n)\n```\n:::\n\n\nAquí la desventaja es que se debe leer de adentro hacia afuera, de derecha a izquierda y que los argumentos terminan separados (problema que se conoce como [Dagwood sandwich](https://es.wikipedia.org/wiki/Dagwood_sandwich)). En resumen, este código es difícil de leer para un ser humano.\n\n### Uso de pipe\n\nFinalmente, podemos usar el pipe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoo_foo %>%\n  saltar(a_traves = bosque) %>%\n  recoger(que = ratones_campo) %>%\n  golpear(en = cabeza)\n```\n:::\n\n\nEsta es nuestra forma preferida, ya que se enfoca en los verbos, no en los sustantivos. Puedes leer esta secuencia de composición de funciones como si fuera un conjunto de acciones imperativas. Foo salta, luego recoge, luego golpea. La desventaja, por supuesto, es que necesitas estar familiarizado con el uso de los pipes. Si nunca has visto `%>%` antes, no tendrás idea acerca de lo que realiza el código. Afortunadamente, la mayoría de la gente entiende la idea fácilmente, así que cuando compartes tu código con otros que no están familiarizados con los pipes, puedes enseñárselos fácilmente.\n\nEl pipe trabaja realizando una \"transformación léxica\": detrás de escena, magrittr reensambla el código en el pipe a una forma que funciona sobrescribiendo un objeto intermedio. Cuando se ejecuta un pipe como el de arriba, magrittr hace algo como esto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmi_pipe <- function(.) {\n  . <- saltar(., a_traves = bosque)\n  . <- recoger(., que = ratones_campo)\n  golpear(., en = la_cabeza)\n}\nmi_pipe(foo_foo)\n```\n:::\n\n\nEsto significa que un pipe no funcionará con dos clases de funciones:\n1. Funciones que usan el entorno actual. Por ejemplo, `assign()` (_asignar_) creará una nueva variable con el nombre dado en el entorno actual:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nassign(\"x\", 10)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10\n```\n:::\n\n```{.r .cell-code}\n\"x\" %>% assign(100)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10\n```\n:::\n:::\n\n\nEl uso de la asignación con el pipe no funcionará porque lo asigna a un entorno temporal usado por `%>%`. Si quieres usar la asignación con un pipe, debes explicitar el entorno:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenv <- environment()\n\"x\" %>% assign(100, envir = env)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100\n```\n:::\n:::\n\n\nOtras funciones con este problema incluyen `get()` y `load()`.\n\n1. Funciones que usan _lazy evaluation_ (evaluación diferida o \"perezosa\"). En R, los argumentos de las funciones son solamente computados cuando la función los usa, no antes de llamar a la función. El pipe computa cada elemento por turno, por lo que no puedes confiar en este comportamiento.\n\nUn caso en el cual esto es un problema es el de `tryCatch()`, que te permite capturar y manejar errores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntryCatch(stop(\"!\"), error = function(e) \"Un error\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Un error\"\n```\n:::\n\n```{.r .cell-code}\nstop(\"!\") %>%\n  tryCatch(error = function(e) \"Un error\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Un error\"\n```\n:::\n:::\n\n\nHay una cantidad relativamente grande de funciones con este comportamiento, que incluye a `try()`, `suppressMessages()` y `suppressWarnings()` en R base.\n\n## Cuándo no usar el pipe\n\nEl pipe es una herramienta poderosa, pero no es la única herramienta a tu disposición ¡y no soluciona todos los problemas! Los pipes son mayoritariamente usados para reescribir una secuencia lineal bastante corta de operaciones. Creemos que deberías buscar otra herramienta cuando:\n\n* Tus pipes son más largos que (digamos) 10 pasos. En ese caso, crea objetos intermedios con nombres significativos. Esto hará la depuración más fácil, porque puedes chequear con mayor facilidad los resultados intermedios. Además, hace más simple entender tu código, ya que los nombres de las variables pueden ayudar a comunicar la intención.\n* Tienes múltiples _inputs_ y _outputs_. Si no hay un objeto principal para ser transformado, sino dos o más objetos siendo combinados juntos, no uses el pipe.\n* Si estás empezando a pensar acerca de un grafo dirigido con una estructura de dependencia compleja. Los pipes son fundamentalmente lineales y usarlos para expresar relaciones complejas, típicamente llevarán a un código confuso.\n\n## Otras herramientas de magrittr\n\nTodos los paquetes del tidyverse automáticamente harán que `%>%` esté disponible, por lo que normalmente no será necesario cargar __magrittr__ explícitamente. De todas formas, hay otras herramientas útiles dentro de magrittr que podrías querer utilizar:\n\n* Cuando se trabaja en un pipe más complejo, a veces es útil llamar a una función por sus efectos secundarios. Tal vez quieras imprimir el objeto actual, o graficarlo, o guardarlo en el disco. Muchas veces, estas funciones no devuelven nada, efectivamente terminando el pipe.\n\nPara solucionar este problema, puedes usar el pipe \"T\". `%T>%`trabaja igual que `%>%`, excepto que  devuelve el lado izquierdo en vez del lado derecho. Se lo llama \"T\" porque literalmente tiene la forma de una T.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrnorm(100) %>%\n  matrix(ncol = 2) %>%\n  plot() %>%\n  str()\n```\n\n::: {.cell-output-display}\n![](18-pipes_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n NULL\n```\n:::\n\n```{.r .cell-code}\nrnorm(100) %>%\n  matrix(ncol = 2) %T>%\n  plot() %>%\n  str()\n```\n\n::: {.cell-output-display}\n![](18-pipes_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:50, 1:2] 0.8451 0.2949 1.002 1.5592 -0.0969 ...\n```\n:::\n:::\n\n\n* Si estás trabajando con funciones que no tienen una API basada en data frames (esto es, pasas vectores individuales, no un data frame o expresiones que serán evaluadas en el contexto de un data frame), puedes encontrar `%$%` útil. Este operador \"explota\" las variables en un dataframe para que te puedas referir a ellas de manera explícita. Esto es útil cuando se trabaja con muchas funciones en R base:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtautos %$%\n  cor(cilindrada, millas)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.8475514\n```\n:::\n:::\n\n\n* Para asignaciones, magrittr provee el operador `%<>%` que te permite reemplazar el código de la siguiente forma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtautos <- mtautos %>%\n  transform(cilindros = cilindros * 2)\n```\n:::\n\n\ncon\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtautos %<>% transform(cilindros = cilindros * 2)\n```\n:::\n\n\nNo somos partidarios de este operador porque creemos que una asignación es una operación especial que siempre debe ser clara cuando sucede.\nEn nuestra opinión, un poco de duplicación (esto es, repetir el nombre de un objeto dos veces) está bien para lograr hacer la asignación más explícita.\n",
    "supporting": [
      "18-pipes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}